const MembershipValueFormula = () => {
  return (
    <math className="text-lg sm:text-2xl border border-white mx-auto p-4 sm:p-10 bg-white text-black rounded-2xl">
      <mrow>
        <msub>
          <mi>μ</mi>
          <mi>j</mi>
        </msub>
        <mrow>
          <mo>(</mo>
          <msub>
            <mi>x</mi>
            <mi>j</mi>
          </msub>
          <mo>)</mo>
        </mrow>
        <mo>=</mo>
        <mfrac>
          <mrow>
            <msup>
              <mrow>
                <mo>[</mo>
                <mfrac>
                  <mn>1</mn>
                  <msub>
                    <mi>d</mi>
                    <mrow>
                      <mi>j</mi>
                      <mi>i</mi>
                    </mrow>
                  </msub>
                </mfrac>
                <mo>]</mo>
              </mrow>
              <mfrac>
                <mn>1</mn>
                <mrow>
                  <mo>(</mo>
                  <mi>m</mi>
                  <mo>-</mo>
                  <mn>1</mn>
                  <mo>)</mo>
                </mrow>
              </mfrac>
            </msup>
          </mrow>
          <mrow>
            <munderover>
              <mo>Σ</mo>
              <mi>k=1</mi>
              <mi>c</mi>
            </munderover>
            <msup>
              <mrow>
                <mo>[</mo>
                <mfrac>
                  <mn>1</mn>
                  <msub>
                    <mi>d</mi>
                    <mrow>
                      <mi>k</mi>
                      <mi>i</mi>
                    </mrow>
                  </msub>
                </mfrac>
                <mo>]</mo>
              </mrow>
              <mfrac>
                <mn>1</mn>
                <mrow>
                  <mo>(</mo>
                  <mi>m</mi>
                  <mo>-</mo>
                  <mn>1</mn>
                  <mo>)</mo>
                </mrow>
              </mfrac>
            </msup>
          </mrow>
        </mfrac>
      </mrow>
      <mo className="ml-[30px]">,</mo>
      <mi>m</mi>
      <mo>=</mo>
      <mn>2</mn>
    </math>
  );
};

export default MembershipValueFormula;
